name: CD
on: 
  push:
    branches:
    - main
jobs: 
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.
      - name: Install Dependencies and execute tests
        run: |
          npm install
      - name: Zip Files
        run: |
          zip -r deployment.zip .
      - name: Send to Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: simplePipeline
          zip_file: deployment.zip